### ISSUE TITLE
Request: add Docker support for Raspberry Pi ARMv7

### ISSUE THREAD

**Issue by CogentRedTester** [azlux/botamusique#316]
I run a Mumble server and Botamusique on my Raspberry Pi running ARMv7, and it would be really useful to have the official docker image support the device.

My docker-compose file contains:
```yml
services:
    xana:
        image: azlux/botamusique
        container_name: XANA
        hostname: XANA
        restart: unless-stopped
        expose:
            - 8181
        environment:
            BAM_CONFIG_file: /config/botamusique.ini
            BAM_CERTIFICATE: /config/botamusique.pem
            BAM_MUSIC_DB: /config/music.db
            BAM_DB: /config/settings-botamusique.db
        volumes:
            - /mnt/hdd/Music:/music
            - ./config:/config
        cpus: 2
```

When I run the container I get:
```
Recreating XANA ... done
Attaching to XANA
XANA    | standard_init_linux.go:228: exec user process caused: exec format error
XANA exited with code 1
```

I attempted to build the container myself, but I kept getting errors and in the end I gave up. I did this some time ago and unfortunately I did not save what the errors were.
